### PR TITLE
Adding Launch Phase Trademark Claims Checking and SecDNS Extensions

### PR DESCRIPTION
**Pull request by rosspace**
I added Launch Phase extensions that allow for checking against Trademark claims. Claims checks have their own command and response object.

I also added SecDNS extensions for creating and updating SecDNS settings. SecDNS is an extension that can be added to the regular DomainCreate and DomainUpdate commands.

### CODE REVIEW

**Comment by ademar** [comment]
Great stuff. Thank you!

**Comment by rosspace** [comment]
No problem. Please let me know when you update your nuget package. Thanks!

**Comment by ademar** [comment]
It is already out :-) 

https://www.nuget.org/packages/EppLib/1.1.62

**Comment by rosspace** [comment]
Awesome, thanks!

**Pull request merged**
